name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-healthcheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: docker build -t devops-service .

      - name: Run container
        run: docker run -d --name svc -p 8080:8080 devops-service

      - name: Wait
        run: sleep 5

      - name: Health endpoint
        run: curl -f http://localhost:8080/health
